controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;

use app\models\EditAccountForm;
use app\models\ReviewShopForm;
use app\models\SingUpForm;
use app\models\Category;
use app\models\Product;
use app\models\Brand;
use app\models\Blog;
use app\models\User;
use app\models\Comment;
use app\models\Cart;
use app\models\TagBlog;
use app\models\EditAccount;
use app\models\File;
use app\models\ResponseForm;
use app\models\SingUpModel;
use app\models\LoginForm;
use app\models\RegForm;
use app\models\Video;

use yii\data\Pagination;
use yii\db\Query;

class SiteController extends AppController {

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }



    public function actionLogin() {    	
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

		$user = new User();
        $singUpNote = $user->singUp();

        $loginFormModel = new LoginForm();
        if ($loginFormModel->load(Yii::$app->request->post()) && $loginFormModel->login()) {
            return $this->goBack();
        }

        $singUpFormModel = new SingUpForm();
        return $this->render('login', [
        	'singUpFormModel' => $singUpFormModel,
        	'loginFormModel' => $loginFormModel,
        	'singUpNote' => $singUpNote        
        ]);
    }


    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionAccount() {
    	$id_user = Yii::$app->session->get('__id');
    	$file = new File($id_user);
    	$user = User::find()->where(['id_user' => $id_user])->one();
    	return $this->render('account',[
    		'user' => $user
    	]);
    }

	public function actionEdit() {
		$id_user = Yii::$app->session->get('__id');
		$EditAccountFormRequest = yii::$app->request->post('EditAccountForm');

		$file = new File($id_user);
		$file->addAvatarFileFromBuffer();
        
		if ($EditAccountFormRequest) {
			User::applyEditAccount($id_user, $EditAccountFormRequest);
            $this->redirect('/site/account');
        }
        
		$user = User::editAccount($id_user);
		$form = new EditAccountForm();
    	return $this->render('edit', [
    		'form' => $form,
    		'user' => $user
    	]);
    }

	public function actionIndex() {
		$brands = Brand::find()->asArray()->all();
		$hits = Product::find()->where(['hit' => '1'])->limit(6)->all();
		$product = new Product();
		$productsInMajorCategories = $product->allProductsToMajorCategory();
		return $this->render('index', [
			'productsInMajorCategories' => $productsInMajorCategories,
			'brands' => $brands,
			'hits' => $hits
		]);
	}

	public function actionContact () {
		return $this->render('contact', [
			'circleOfHands' => $circleOfHands
		]);
	}

}

views/site/account.php
<section id="cart_items">
    <div class="container">
        
        <div class="user-cabinet">
            
            <div class="head-user-cabinet"></div>

            <div class="user-avater-block">
                <div>
                    <img src="/web/images/users/<?= $user['img_user'] ?>" class="user-avatar"/>
                </div>
            </div>

            <p><b><?=$user->name?> <?=$user->middle_name?> <?=$user->last_name?></b></p>

            <table>
                <tr>
                    <td>Display name:</td>
                    <td> <?= $user['display_name'] ?> </td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>

                <tr>
                    <td>Email:</td>
                    <td><?= $user['email'] ?></td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>
                <tr>
                    <td>Country:</td>
                    <td><?= $user['country'] ?></td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td><?= $user['city'] ?> <?= $user['street'] ?> <?= $user['house'] ?> <?= $user['apartment'] ?> </td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>
                <tr>
                    <td>Postal Code:</td>
                    <td><?= $user['postal_code'] ?></td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>
                <tr>
                    <td>Phone:</td>
                    <td><?= $user['phone'] ?></td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>
                <tr>
                    <td>Mobile phone:</td>
                    <td><?= $user['mobile_phone'] ?></td>
                </tr>

                <tr>
                    <td><hr></td>
                    <td><hr></td>
                </tr>              
            </table>

            <div class="edit-user">
                <a href="<?=yii::$app->urlManager->createUrl('site/edit')?>">Edit user information</a>
            </div>
            
        <div class="head-user-cabinet"></div>
        </div>

    </div>

</section> <!--/#cart_items-->

views/site/contact.php
<?php
	$this->title = "E-SHOPPER | Contuct Us";
?>

 <div id="contact-page" class="container">
	<div class="bg">
    	<div class="row">    		
    		<div class="col-sm-12">    			   			
				<h2 class="title text-center">Contact <strong>Us</strong></h2>    			    				    				
				<div id="gmap" class="contact-map">
				</div>
			</div>			 		
		</div>    	
		<div class="row">  	
    		<div class="col-sm-8">
    			<div class="contact-form">
    				<h2 class="title text-center">Get In Touch</h2>
    				<div class="status alert alert-success" style="display: none"></div>
			    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
			            <div class="form-group col-md-6">
			                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
			            </div>
			            <div class="form-group col-md-6">
			                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
			            </div>
			            <div class="form-group col-md-12">
			                <input type="text" name="subject" class="form-control" required="required" placeholder="Subject">
			            </div>
			            <div class="form-group col-md-12">
			                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
			            </div>                        
			            <div class="form-group col-md-12">
			                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
			            </div>
			        </form>
    			</div>
    		</div>
    		<div class="col-sm-4">
    			<div class="contact-info">
    				<h2 class="title text-center">Contact Info</h2>
    				<address>
    					<p>E-Shopper Inc.</p>
						<p>935 W. Webster Ave New Streets Chicago, IL 60614, NY</p>
						<p>Newyork USA</p>
						<p>Mobile: +2346 17 38 93</p>
						<p>Fax: 1-714-252-0026</p>
						<p>Email: info@e-shopper.com</p>
    				</address>
    				<div class="social-networks">
    					<h2 class="title text-center">Social Networking</h2>
						<ul>
							<li>
								<a href="#"><i class="fa fa-facebook"></i></a>
							</li>
							<li>
								<a href="#"><i class="fa fa-twitter"></i></a>
							</li>
							<li>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</li>
							<li>
								<a href="#"><i class="fa fa-youtube"></i></a>
							</li>
						</ul>
    				</div>
    			</div>
			</div>    			
    	</div>  
	</div>	
</div><!--/#contact-page-->

views/site/edit.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
?>

<section id="cart_items">
    <div class="container">

        <div class="user-cabinet">

            <?php $f = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

                <div class="head-user-cabinet"></div>

                <div class="user-avatar-block">
                    <div>
                        <img src="/web/images/users/<?= $user['img_user'] ?>" class="user-avatar"/>

                        <div class="">
                            <label for="add-avatar">
                                <div class="file-upload-label">
                                    <div class=''>
                                        UPLOAD
                                    </div>
                                </div>
                            </label>

                            <input type="file" id="add-avatar" name="avatar" class="add-avatar">
                            <?= $f->field($form, 'img_user')->textInput(['class' => 'add-avatar'])->label(false) ?>
                        </div>

                    </div>
                </div>

                <table>

                    <tr>
                        <td>Name</td>
                        <td><?= $f->field($form, 'name')->label(false)->textInput(['value' => $user->name]) ?></td>
                    </tr>

                    <tr>
                        <td>Middle name</td>
                        <td><?= $f->field($form, 'middle_name')->label(false)->textInput(['value' => $user->middle_name]) ?></td>
                    </tr>

                    <tr>
                        <td>Lastname</td>
                        <td><?= $f->field($form, 'last_name')->label(false)->textInput(['value' => $user->last_name]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>

                    <tr>
                        <td>Display name:</td>
                        <td><?= $f->field($form, 'display_name')->label(false)->textInput(['value' => $user->display_name]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>

                    <tr>
                        <td>Email:</td>
                        <td><?= $f->field($form, 'email')->label(false)->textInput(['value' => $user->email]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>

                    <tr>
                        <td>Country:</td>
                        <td><?= $f->field($form, 'country')->label(false)->textInput(['value' => $user->country]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>


                    <tr>
                        <td>City:</td>
                        <td><?= $f->field($form, 'street')->label(false)->textInput(['value' => $user->city]) ?></td>
                    </tr>

                    <tr>
                        <td>Street:</td>
                        <td><?= $f->field($form, 'street')->label(false)->textInput(['value' => $user->street]) ?></td>
                    </tr>

                    <tr>
                        <td>House:</td>
                        <td><?= $f->field($form, 'house')->label(false)->textInput(['value' => $user->house]) ?></td>
                    </tr>

                    <tr>
                        <td>Apartment:</td>
                        <td><?= $f->field($form, 'house')->label(false)->textInput(['value' => $user->apartment]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>

                    <tr>
                        <td>Postal Code:</td>
                        <td><?= $f->field($form, 'postal_code')->label(false)->textInput(['value' => $user->postal_code]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>

                    <tr>
                        <td>Phone:</td>
                        <td><?= $f->field($form, 'phone')->label(false)->textInput(['value' => $user->phone]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>

                    <tr>
                        <td>Mobile phone:</td>
                        <td><?= $f->field($form, 'mobile_phone')->label(false)->textInput(['value' => $mobile_phone]) ?></td>
                    </tr>

                    <tr>
                        <td><hr></td><td><hr></td>
                    </tr>              
                </table>

                <div class="confirm-edit-form"><button class="confirm-edit-form" type="submit">CONFIRM</button></div>

            <?php ActiveForm::end() ?>

      
        <div class="head-user-cabinet"></div>
        </div>
    </div>

</section> <!--/#cart_items-->

views/site/login.php
<?php use yii\widgets\ActiveForm; ?>
<?php use yii\helpers\Html; ?>

    <section id="form"><!--form-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-1">
                    <div class="login-form"><!--login form-->
                        <h2>Login to your account</h2>

                        <?php $formLog = ActiveForm::begin([
                            'id' => 'login-form',
                            'fieldConfig' => [
                                'labelOptions' => ['class' => 'col-lg-1 control-label'],
                            ]
                        ]); ?>

                            <?=$formLog->field($loginFormModel, 'username')->textInput(['placeholder' => 'username'])->label(false)?>

                            <?=$formLog->field($loginFormModel, 'password')->textInput(['placeholder' => 'password', 'type' => 'password'])->label(false)?>

                            <span><?= $formLog->field($loginFormModel, 'rememberMe')->checkbox() ?></span>

                            <button type="submit" class="btn btn-default">Login</button>
                        <?php ActiveForm::end(); ?>



                    </div><!--/login form-->
                </div>
                        
<!--
                <div class="col-sm-1">
                    <h2 class="or">OR</h2>
                </div>
-->
                <div class="col-sm-4">
                    <div class="signup-form">
                        <h2>New User Signup!</h2>
                        <?php $formReg = ActiveForm::begin(); ?>
                            
                            <?= $formReg->field($singUpFormModel, 'username')->textInput(['placeholder' => 'username'])->label(false) ?>
                            
                            <?= $formReg->field($singUpFormModel, 'password')->textInput(['placeholder' => 'password'])->label(false) ?>
                            
                            <?= $formReg->field($singUpFormModel, 'confirm_password')->textInput(['placeholder' => 'confirm password'])->label(false) ?>

                            <button type="submit" class="btn btn-default">Signup</button> 

                            <div <?php  if($sing_up_note === 'Регистрация прошла успешно') ?> 
                                class="note-error" 
                            >

                                <?=$singUpNote?>
                            
                            </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                </div>

            </div>
        </div>
    </section>